-- MySQL Script generated by MySQL Workbench
-- Mon Sep 29 10:02:48 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema klmvluchten
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema klmvluchten
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `klmvluchten` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema dbfirst
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbfirst
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbfirst` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `klmvluchten` ;

-- -----------------------------------------------------
-- Table `klmvluchten`.`Vlucht`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `klmvluchten`.`Vlucht` (
  `idklmvluchten` INT NOT NULL AUTO_INCREMENT,
  `vluchtnummer` VARCHAR(45) NULL,
  `vliegtuig type` VARCHAR(45) NULL,
  `vertrektijd` DATETIME NULL,
  `aankomst tijd` DATETIME NULL,
  `vertrek vluchthaven` DATETIME NULL,
  `aankomst vlucht haven` DATETIME NULL,
  PRIMARY KEY (`idklmvluchten`),
  UNIQUE INDEX `idklmvluchten_UNIQUE` (`idklmvluchten` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `klmvluchten`.`Personeel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `klmvluchten`.`Personeel` (
  `idPersoneel` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersoneel`),
  UNIQUE INDEX `idPersoneel_UNIQUE` (`idPersoneel` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `klmvluchten`.`Vlucht_has_Personeel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `klmvluchten`.`Vlucht_has_Personeel` (
  `Vlucht_idklmvluchten` INT NOT NULL,
  `Personeel_idPersoneel` INT NOT NULL,
  PRIMARY KEY (`Vlucht_idklmvluchten`, `Personeel_idPersoneel`),
  INDEX `fk_Vlucht_has_Personeel_Personeel1_idx` (`Personeel_idPersoneel` ASC) VISIBLE,
  INDEX `fk_Vlucht_has_Personeel_Vlucht_idx` (`Vlucht_idklmvluchten` ASC) VISIBLE,
  CONSTRAINT `fk_Vlucht_has_Personeel_Vlucht`
    FOREIGN KEY (`Vlucht_idklmvluchten`)
    REFERENCES `klmvluchten`.`Vlucht` (`idklmvluchten`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vlucht_has_Personeel_Personeel1`
    FOREIGN KEY (`Personeel_idPersoneel`)
    REFERENCES `klmvluchten`.`Personeel` (`idPersoneel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `dbfirst` ;

-- -----------------------------------------------------
-- Table `dbfirst`.`bordspellen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfirst`.`bordspellen` (
  `idbordspellen` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(250) NOT NULL,
  `aantal spelers` INT NOT NULL,
  `beschrijving` VARCHAR(500) NOT NULL,
  `coop` INT NOT NULL,
  PRIMARY KEY (`idbordspellen`),
  UNIQUE INDEX `idbordspellen_UNIQUE` (`idbordspellen` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
