version: '3.9'

# Services
services:
 # PHP FPM Service
  php:
    image: wodby/php:latest
    volumes:
      - './html:/var/www/html'
    depends_on:
      - mariadb
# Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - 88:80
    links:
      - 'php'
    volumes:
      - './html:/var/www/html'
      - './docker/nginx:/etc/nginx/conf.d'
    depends_on:
      - php
  # MariaDB Service
  mariadb:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_SCHEMA_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 3308:3306

  # php myadmin in an external image
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "1088:80"

# Volumes
volumes:
  mysqldata: